import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import ReduxProvider from "@/components/ReduxProvider";
import { Toaster } from "react-hot-toast";
import FooterPage from "@/components/Footer";
import NextAuthProvider from "@/Providers/NextAuthSeasionProviders";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "eCommerce-Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ReduxProvider>
          <NextAuthProvider>
            <NavBar />
            <Toaster />
            {children}
            <div className="mt-24"> <FooterPage />
            </div>
          </NextAuthProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}